/**
 * PAWARTA — Daftar Permission Sistem (Type-Safe Constants)
 *
 * Konvensi penamaan: MODUL_ENTITAS_AKSI
 * Contoh: SURAT_MASUK_READ, IAM_USER_CREATE
 *
 * Permission ini wajib sinkron dengan data di tabel `permissions` (di-seed via seed-rbac.ts).
 */

// ============================================================
// MODUL: MASTER DATA
// ============================================================
export const PERM = {
  // --- Sekolah ---
  MASTER_SEKOLAH_READ: 'MASTER_SEKOLAH_READ',
  MASTER_SEKOLAH_UPDATE: 'MASTER_SEKOLAH_UPDATE',

  // --- Pegawai ---
  MASTER_PEGAWAI_READ: 'MASTER_PEGAWAI_READ',
  MASTER_PEGAWAI_CREATE: 'MASTER_PEGAWAI_CREATE',
  MASTER_PEGAWAI_UPDATE: 'MASTER_PEGAWAI_UPDATE',
  MASTER_PEGAWAI_DELETE: 'MASTER_PEGAWAI_DELETE',

  // --- Jabatan ---
  MASTER_JABATAN_READ: 'MASTER_JABATAN_READ',
  MASTER_JABATAN_CREATE: 'MASTER_JABATAN_CREATE',
  MASTER_JABATAN_UPDATE: 'MASTER_JABATAN_UPDATE',
  MASTER_JABATAN_DELETE: 'MASTER_JABATAN_DELETE',

  // --- Unit Kerja ---
  MASTER_UNIT_KERJA_READ: 'MASTER_UNIT_KERJA_READ',
  MASTER_UNIT_KERJA_CREATE: 'MASTER_UNIT_KERJA_CREATE',
  MASTER_UNIT_KERJA_UPDATE: 'MASTER_UNIT_KERJA_UPDATE',
  MASTER_UNIT_KERJA_DELETE: 'MASTER_UNIT_KERJA_DELETE',

  // --- Instansi ---
  MASTER_INSTANSI_READ: 'MASTER_INSTANSI_READ',
  MASTER_INSTANSI_CREATE: 'MASTER_INSTANSI_CREATE',
  MASTER_INSTANSI_UPDATE: 'MASTER_INSTANSI_UPDATE',
  MASTER_INSTANSI_DELETE: 'MASTER_INSTANSI_DELETE',

  // --- Kelas & Siswa ---
  MASTER_KELAS_READ: 'MASTER_KELAS_READ',
  MASTER_KELAS_CREATE: 'MASTER_KELAS_CREATE',
  MASTER_KELAS_UPDATE: 'MASTER_KELAS_UPDATE',
  MASTER_KELAS_DELETE: 'MASTER_KELAS_DELETE',
  MASTER_SISWA_READ: 'MASTER_SISWA_READ',
  MASTER_SISWA_CREATE: 'MASTER_SISWA_CREATE',
  MASTER_SISWA_UPDATE: 'MASTER_SISWA_UPDATE',
  MASTER_SISWA_DELETE: 'MASTER_SISWA_DELETE',

  // --- Jenis Surat ---
  MASTER_JENIS_SURAT_READ: 'MASTER_JENIS_SURAT_READ',
  MASTER_JENIS_SURAT_CREATE: 'MASTER_JENIS_SURAT_CREATE',
  MASTER_JENIS_SURAT_UPDATE: 'MASTER_JENIS_SURAT_UPDATE',
  MASTER_JENIS_SURAT_DELETE: 'MASTER_JENIS_SURAT_DELETE',

  // --- Klasifikasi Surat ---
  MASTER_KLASIFIKASI_READ: 'MASTER_KLASIFIKASI_READ',
  MASTER_KLASIFIKASI_CREATE: 'MASTER_KLASIFIKASI_CREATE',
  MASTER_KLASIFIKASI_UPDATE: 'MASTER_KLASIFIKASI_UPDATE',
  MASTER_KLASIFIKASI_DELETE: 'MASTER_KLASIFIKASI_DELETE',

  // --- Penandatangan ---
  MASTER_PENANDATANGAN_READ: 'MASTER_PENANDATANGAN_READ',
  MASTER_PENANDATANGAN_CREATE: 'MASTER_PENANDATANGAN_CREATE',
  MASTER_PENANDATANGAN_UPDATE: 'MASTER_PENANDATANGAN_UPDATE',
  MASTER_PENANDATANGAN_DELETE: 'MASTER_PENANDATANGAN_DELETE',

  // --- Kop Surat / Header ---
  MASTER_KOP_SURAT_READ: 'MASTER_KOP_SURAT_READ',
  MASTER_KOP_SURAT_CREATE: 'MASTER_KOP_SURAT_CREATE',
  MASTER_KOP_SURAT_UPDATE: 'MASTER_KOP_SURAT_UPDATE',
  MASTER_KOP_SURAT_DELETE: 'MASTER_KOP_SURAT_DELETE',

  // --- Template Surat ---
  MASTER_TEMPLATE_READ: 'MASTER_TEMPLATE_READ',
  MASTER_TEMPLATE_CREATE: 'MASTER_TEMPLATE_CREATE',
  MASTER_TEMPLATE_UPDATE: 'MASTER_TEMPLATE_UPDATE',
  MASTER_TEMPLATE_DELETE: 'MASTER_TEMPLATE_DELETE',

  // --- Prioritas & Sifat Surat ---
  MASTER_PRIORITAS_READ: 'MASTER_PRIORITAS_READ',
  MASTER_PRIORITAS_MANAGE: 'MASTER_PRIORITAS_MANAGE',
  MASTER_SIFAT_SURAT_READ: 'MASTER_SIFAT_SURAT_READ',
  MASTER_SIFAT_SURAT_MANAGE: 'MASTER_SIFAT_SURAT_MANAGE',

  // ============================================================
  // MODUL: SURAT MASUK
  // ============================================================
  SURAT_MASUK_READ: 'SURAT_MASUK_READ',
  SURAT_MASUK_CREATE: 'SURAT_MASUK_CREATE',
  SURAT_MASUK_UPDATE: 'SURAT_MASUK_UPDATE',
  SURAT_MASUK_DELETE: 'SURAT_MASUK_DELETE',
  SURAT_MASUK_UPLOAD_LAMPIRAN: 'SURAT_MASUK_UPLOAD_LAMPIRAN',
  SURAT_MASUK_DISTRIBUSI: 'SURAT_MASUK_DISTRIBUSI',
  SURAT_MASUK_DISPOSISI: 'SURAT_MASUK_DISPOSISI',
  SURAT_MASUK_DISPOSISI_SAYA: 'SURAT_MASUK_DISPOSISI_SAYA',
  SURAT_MASUK_AGENDA: 'SURAT_MASUK_AGENDA',

  // ============================================================
  // MODUL: SURAT KELUAR
  // ============================================================
  SURAT_KELUAR_READ: 'SURAT_KELUAR_READ',
  SURAT_KELUAR_CREATE: 'SURAT_KELUAR_CREATE',
  SURAT_KELUAR_UPDATE: 'SURAT_KELUAR_UPDATE',
  SURAT_KELUAR_DELETE: 'SURAT_KELUAR_DELETE',
  SURAT_KELUAR_SUBMIT: 'SURAT_KELUAR_SUBMIT',
  SURAT_KELUAR_REVIEW: 'SURAT_KELUAR_REVIEW',
  SURAT_KELUAR_APPROVE: 'SURAT_KELUAR_APPROVE',
  SURAT_KELUAR_TTD: 'SURAT_KELUAR_TTD',
  SURAT_KELUAR_PUBLISH: 'SURAT_KELUAR_PUBLISH',
  SURAT_KELUAR_DISTRIBUSI: 'SURAT_KELUAR_DISTRIBUSI',

  // ============================================================
  // MODUL: SURAT SISWA
  // ============================================================
  SURAT_SISWA_READ: 'SURAT_SISWA_READ',
  SURAT_SISWA_CREATE: 'SURAT_SISWA_CREATE',
  SURAT_SISWA_UPDATE: 'SURAT_SISWA_UPDATE',
  SURAT_SISWA_DELETE: 'SURAT_SISWA_DELETE',
  SURAT_SISWA_APPROVE: 'SURAT_SISWA_APPROVE',

  // ============================================================
  // MODUL: ARSIP DIGITAL
  // ============================================================
  ARSIP_READ: 'ARSIP_READ',
  ARSIP_CREATE: 'ARSIP_CREATE',
  ARSIP_UPDATE: 'ARSIP_UPDATE',
  ARSIP_DELETE: 'ARSIP_DELETE',
  ARSIP_PINJAM: 'ARSIP_PINJAM',
  ARSIP_APPROVE_PINJAM: 'ARSIP_APPROVE_PINJAM',
  ARSIP_RETENSI: 'ARSIP_RETENSI',
  ARSIP_MUSNAH: 'ARSIP_MUSNAH',

  // ============================================================
  // MODUL: IAM (Pengguna & Role)
  // ============================================================
  IAM_USER_READ: 'IAM_USER_READ',
  IAM_USER_CREATE: 'IAM_USER_CREATE',
  IAM_USER_UPDATE: 'IAM_USER_UPDATE',
  IAM_USER_DELETE: 'IAM_USER_DELETE',
  IAM_USER_RESET_PASSWORD: 'IAM_USER_RESET_PASSWORD',
  IAM_ROLE_READ: 'IAM_ROLE_READ',
  IAM_ROLE_MANAGE: 'IAM_ROLE_MANAGE',
  IAM_LOGIN_LOG_READ: 'IAM_LOGIN_LOG_READ',

  // ============================================================
  // MODUL: SISTEM & PENGATURAN
  // ============================================================
  SISTEM_KONFIGURASI: 'SISTEM_KONFIGURASI',
  SISTEM_NOTIFIKASI: 'SISTEM_NOTIFIKASI',
  SISTEM_API_KEY: 'SISTEM_API_KEY',
  SISTEM_WEBHOOK: 'SISTEM_WEBHOOK',
  SISTEM_AUTOMATION: 'SISTEM_AUTOMATION',
  SISTEM_BACKUP: 'SISTEM_BACKUP',
  SISTEM_LOG_READ: 'SISTEM_LOG_READ',
} as const;

export type Permission = (typeof PERM)[keyof typeof PERM];

// ============================================================
// DAFTAR ROLE RESMI SISTEM
// ============================================================
export const ROLES = {
  SUPER_ADMIN: 'Super Admin',
  KEPALA_SEKOLAH: 'Kepala Sekolah',
  KTU: 'Kepala Tata Usaha',
  STAF_TU: 'Staf TU',
  GURU: 'Guru',
  ARSIPARIS: 'Arsiparis',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];
