/**
 * Standar Tata Naskah Dinas Berdasarkan:
 * Peraturan Bupati Sumedang Nomor 9 Tahun 2026
 * tentang Tata Naskah Dinas di Lingkungan Pemerintah Daerah
 */

export interface StandarJenisNaskahDinas {
  kode: string;
  nama: string;
  kategori: 'Naskah Dinas Arahan' | 'Naskah Dinas Korespondensi' | 'Naskah Dinas Khusus';
  subKategori: 'Pengaturan' | 'Penetapan' | 'Penugasan' | 'Internal' | 'Eksternal' | 'Khusus';
  fontFamily: 'Bookman Old Style' | 'Arial';
  fontSize: number; // 12 pt
  lineSpacing: string; // '1.0' atau '1.15'
  marginKiri: string; // '3.0cm'
  marginKanan: string; // '2.0cm'
  marginAtas: string; // '2.5cm'
  marginBawah: string; // '2.5cm'
  ukuranKertas: 'F4';
  deskripsi: string;
}

export const STANDAR_TATA_LETAK = {
  kertas: {
    jenis: 'Houtvrij Schrijfpapier (HVS)',
    ukuran: 'F4',
    gramaturMin: 70, // gr/m2
  },
  margin: {
    kiri: '3.0cm',
    kanan: '2.0cm',
    atas: '2.5cm', // atau 2 spasi di bawah kop
    bawah: '2.5cm',
  },
  tipografi: {
    pengaturanDanPenetapan: {
      fontFamily: 'Bookman Old Style',
      fontSize: 12,
      lineSpacing: '1.0',
    },
    korespondensiDanKhusus: {
      fontFamily: 'Arial',
      fontSize: 12,
      lineSpacing: '1.15',
    },
  },
  tinta: {
    pengetikan: 'Hitam',
    tandaTanganDanParaf: 'Biru Tua',
    stempelBiasa: 'Ungu',
    stempelRahasia: 'Merah',
  },
} as const;

export const DAFTAR_JENIS_NASKAH_DINAS: StandarJenisNaskahDinas[] = [
  // ==========================================================================
  // 1. NASKAH DINAS ARAHAN
  // ==========================================================================
  // A. Pengaturan (Bookman Old Style 12pt, Spasi 1.0)
  {
    kode: 'PERDA',
    nama: 'Peraturan Daerah',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Pengaturan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Peraturan perundang-undangan yang dibentuk oleh DPRD dengan persetujuan bersama Bupati.',
  },
  {
    kode: 'PERBUP',
    nama: 'Peraturan Bupati',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Pengaturan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Peraturan yang ditetapkan oleh Bupati untuk menjalankan peraturan perundang-undangan.',
  },
  {
    kode: 'PER_DPRD',
    nama: 'Peraturan DPRD',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Pengaturan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Peraturan yang ditetapkan oleh Dewan Perwakilan Rakyat Daerah.',
  },

  // B. Penetapan (Bookman Old Style 12pt, Spasi 1.0)
  {
    kode: 'KEPBUP',
    nama: 'Keputusan Bupati',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penetapan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Naskah dinas penetapan yang ditetapkan oleh Bupati bersifat konkret, individual, dan final.',
  },
  {
    kode: 'KEP_DPRD',
    nama: 'Keputusan DPRD',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penetapan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Naskah dinas penetapan yang ditetapkan oleh DPRD.',
  },
  {
    kode: 'KEP_PIM_DPRD',
    nama: 'Keputusan Pimpinan DPRD',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penetapan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Naskah dinas penetapan yang ditetapkan oleh Pimpinan DPRD.',
  },
  {
    kode: 'KEP_BK_DPRD',
    nama: 'Keputusan Badan Kehormatan DPRD',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penetapan',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Naskah dinas penetapan yang ditetapkan oleh Badan Kehormatan DPRD.',
  },

  // C. Penugasan (Arial 12pt)
  {
    kode: 'SP',
    nama: 'Surat Perintah',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penugasan',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Berisi perintah atasan kepada bawahan untuk melaksanakan pekerjaan tertentu di luar tugas dan fungsi.',
  },
  {
    kode: 'ST',
    nama: 'Surat Tugas',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penugasan',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Berisi tugas atasan kepada bawahan untuk melaksanakan perintah pekerjaan sesuai dengan tugas dan fungsinya.',
  },
  {
    kode: 'SPD',
    nama: 'Surat Perjalanan Dinas',
    kategori: 'Naskah Dinas Arahan',
    subKategori: 'Penugasan',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Dokumen yang diterbitkan oleh PPK dalam rangka pelaksanaan perjalanan dinas pejabat/ASN/pihak lain.',
  },

  // ==========================================================================
  // 2. NASKAH DINAS KORESPONDENSI
  // ==========================================================================
  // A. Internal (Arial 12pt)
  {
    kode: 'ND',
    nama: 'Nota Dinas',
    kategori: 'Naskah Dinas Korespondensi',
    subKategori: 'Internal',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Sarana komunikasi kedinasan antar pejabat / atasan-bawahan di lingkungan internal Perangkat Daerah.',
  },
  {
    kode: 'MEMO',
    nama: 'Memo',
    kategori: 'Naskah Dinas Korespondensi',
    subKategori: 'Internal',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Informasi kedinasan bersifat mengingatkan suatu masalah, arahan, atau pendapat dari atasan kepada bawahan.',
  },
  {
    kode: 'DISPOSISI',
    nama: 'Lembar Disposisi',
    kategori: 'Naskah Dinas Korespondensi',
    subKategori: 'Internal',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Petunjuk tertulis singkat dari atasan kepada bawahan mengenai tindak lanjut terhadap naskah dinas masuk.',
  },

  // B. Eksternal (Arial 12pt)
  {
    kode: 'SD',
    nama: 'Surat Dinas',
    kategori: 'Naskah Dinas Korespondensi',
    subKategori: 'Eksternal',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Sarana komunikasi tertulis resmi dengan pihak eksternal atau antar instansi pemerintah.',
  },

  // ==========================================================================
  // 3. NASKAH DINAS KHUSUS (22 JENIS)
  // ==========================================================================
  {
    kode: 'INS',
    nama: 'Instruksi',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Berisi perintah/arahan Bupati sesuai dengan ketentuan peraturan perundang-undangan.',
  },
  {
    kode: 'SE',
    nama: 'Surat Edaran',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Berisi pemberitahuan, penjelasan, atau petunjuk cara melaksanakan hal tertentu yang penting dan mendesak.',
  },
  {
    kode: 'SKU',
    nama: 'Surat Kuasa',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Pemberian kuasa kepada pihak lain untuk bertindak atas namanya dalam rangka kedinasan.',
  },
  {
    kode: 'BA',
    nama: 'Berita Acara',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Pernyataan pelaksanaan suatu kegiatan pada waktu dan tempat tertentu yang ditandatangani para pihak.',
  },
  {
    kode: 'SKET',
    nama: 'Surat Keterangan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Berisi penjelasan subjek dan objek untuk kepentingan kedinasan atau tujuan tertentu.',
  },
  {
    kode: 'SPENG',
    nama: 'Surat Pengantar',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Digunakan untuk mengantarkan naskah dinas atau barang kedinasan.',
  },
  {
    kode: 'PENG',
    nama: 'Pengumuman',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Pemberitahuan yang bersifat umum dari pejabat yang berwenang kepada publik atau pegawai.',
  },
  {
    kode: 'LAP',
    nama: 'Laporan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Pemberitahuan tentang pelaksanaan kegiatan atau kejadian tertentu kepada pimpinan.',
  },
  {
    kode: 'TS',
    nama: 'Telaahan Staf',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Analisis pertimbangan, pendapat, dan saran secara sistematis terhadap suatu permasalahan dari bawahan ke atasan.',
  },
  {
    kode: 'NOT',
    nama: 'Notula',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Catatan yang berisi jalannya proses sidang atau rapat dinas.',
  },
  {
    kode: 'UND',
    nama: 'Surat Undangan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Undangan resmi kepada pejabat/pegawai/pihak luar untuk menghadiri acara kedinasan.',
  },
  {
    kode: 'SPMT',
    nama: 'Surat Pernyataan Melaksanakan Tugas',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Pernyataan pejabat berwenang bahwa seorang pegawai telah nyata melaksanakan tugas.',
  },
  {
    kode: 'SPGL',
    nama: 'Surat Panggilan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Pemanggilan dari pejabat yang berwenang kepada pegawai untuk menghadap.',
  },
  {
    kode: 'SIZIN',
    nama: 'Surat Izin',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Persetujuan terhadap permohonan yang dikeluarkan oleh pejabat berwenang sesuai regulasi.',
  },
  {
    kode: 'LD',
    nama: 'Lembaran Daerah',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Penerbitan resmi Pemerintah Daerah untuk mengundangkan Peraturan Daerah.',
  },
  {
    kode: 'BD',
    nama: 'Berita Daerah',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Bookman Old Style',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Penerbitan resmi untuk mengundangkan Peraturan Bupati dan Peraturan DPRD.',
  },
  {
    kode: 'REK',
    nama: 'Rekomendasi',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Keterangan/catatan pejabat berwenang mengenai suatu hal sebagai bahan pertimbangan.',
  },
  {
    kode: 'RAD',
    nama: 'Radiogram',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.0',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Pesan tertulis resmi yang dikirim melalui telekomunikasi elektronik / radio naskah dinas.',
  },
  {
    kode: 'STTPP',
    nama: 'Surat Tanda Tamat Pendidikan dan Pelatihan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Tanda bukti seseorang telah lulus/mengikuti pendidikan dan pelatihan tertentu.',
  },
  {
    kode: 'SERT',
    nama: 'Sertifikat',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi: 'Tanda bukti telah mengikuti bimbingan teknis, workshop, seminar, atau sejenisnya.',
  },
  {
    kode: 'PIAGAM',
    nama: 'Piagam Penghargaan',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Penghargaan atas prestasi yang telah dicapai atau keteladanan yang telah diwujudkan.',
  },
  {
    kode: 'PERJ',
    nama: 'Surat Perjanjian',
    kategori: 'Naskah Dinas Khusus',
    subKategori: 'Khusus',
    fontFamily: 'Arial',
    fontSize: 12,
    lineSpacing: '1.15',
    marginKiri: '3.0cm',
    marginKanan: '2.0cm',
    marginAtas: '2.5cm',
    marginBawah: '2.5cm',
    ukuranKertas: 'F4',
    deskripsi:
      'Kesepakatan bersama yang mengikat antar kedua belah pihak atau lebih untuk perbuatan hukum.',
  },
];
